# Generated by Django 3.2 on 2021-04-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhfind', '0003_auto_20210426_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='region',
            field=models.CharField(max_length=255, verbose_name='запрос региона'),
        ),
    ]
