# Generated by Django 3.2 on 2021-04-26 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hhfind', '0004_alter_request_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Req',
        ),
    ]
